apiVersion: batch/v1
kind: Job
metadata:
  name: fio
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - image: ljishen/fio
        name: fio
        command:
        - fio
        - --runtime
        - "60"
        - /root/config/fio.ini
        volumeMounts:
        - name: config
          mountPath: "/root/config"
        - name: volume
          mountPath: "/mnt/azure"
      restartPolicy: Never
      volumes:
      - name: config
        configMap:
          name: fio-config
      - name: volume
        persistentVolumeClaim:
          claimName: burstable-managed-csi-premium