kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-ultradisk-encrypted
provisioner: disk.csi.azure.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  skuname: UltraSSD_LRS
  kind: managed
  fsType: xfs
  diskEncryptionSetID: /subscriptions/$(subscription_id)/resourceGroups/playground-aks-des/providers/Microsoft.Compute/diskEncryptionSets/des
  diskIopsReadWrite: "2000"
  diskMbpsReadWrite: "320"
  cachingMode: None
